version: "3.9"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_demo
    networks:
      - demo-bridge
    volumes:
      - demo-volume:/var/lib/mysql
      - ./sqls:/docker-entrypoint-initdb.d
    #由於mysql image自己就有定義一個docker-entrypoint-initdb.d資料夾是在資料庫初始化就執行的資料夾，使用volumes掛載進去給docker-entrypoint-initdb.d資料夾需要執行的sql或sh檔案    
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skill
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  springio-api: 
    depends_on:
      - mysql
    image: springio-api:1.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: springio-api_demo
    networks:
      - demo-bridge
    ports:
      - 8080:8080
    restart: always
networks:
  demo-bridge:
volumes:
  demo-volume:
